version: "3.7"

services:
  app:
    build: .
    container_name: rabbitmq-socketio-nodejs-react
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - rabbitmq_go_net
    depends_on:
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=60 -- npm run start'
    

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=username"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

  
networks:
  rabbitmq_go_net:  
    driver: bridge